version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/web
hooks:
  AfterInstall:
    - location: aws-scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: aws-scripts/start_server.sh
      timeout: 300
      runas: root
